[2025-09-16T16:19:32.751+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline_postgres.transform manual__2025-09-16T16:19:27.646070+00:00 [queued]>
[2025-09-16T16:19:32.756+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline_postgres.transform manual__2025-09-16T16:19:27.646070+00:00 [queued]>
[2025-09-16T16:19:32.756+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-09-16T16:19:32.764+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform> on 2025-09-16 16:19:27.646070+00:00
[2025-09-16T16:19:32.769+0000] {standard_task_runner.py:57} INFO - Started process 209 to run task
[2025-09-16T16:19:32.771+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_pipeline_postgres', 'transform', 'manual__2025-09-16T16:19:27.646070+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados.py', '--cfg-path', '/tmp/tmpc1rzl8xi']
[2025-09-16T16:19:32.772+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask transform
[2025-09-16T16:19:32.801+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_pipeline_postgres.transform manual__2025-09-16T16:19:27.646070+00:00 [running]> on host 5a564937ffb3
[2025-09-16T16:19:32.846+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_pipeline_postgres' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T16:19:27.646070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T16:19:27.646070+00:00'
[2025-09-16T16:19:32.859+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-16T16:19:32.865+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=crypto_pipeline_postgres, task_id=transform, execution_date=20250916T161927, start_date=20250916T161932, end_date=20250916T161932
[2025-09-16T16:19:32.903+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-16T16:19:32.917+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
